[package]
name = "luhn"
version = "0.1.0"
authors = ["zperk13 <zperk13>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
